server:
  port: 8080
spring:
  application:
    name: datum-srv-clientes
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/datum_db?useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME:user_datum}
    password: ${DB_PASSWORD:C0ntrol3Xyz21}
  devtools:
    add-properties: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    show-sql: false
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${AUTH_HOST:localhost}:${AUTH_PORT:9000}
  rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: ${RMQ_PORT:5672}
    virtual-host: ${RMQ_VIRTUAL_HOST:/}
    username: ${RMQ_USERNAME:guest}
    password: ${RMQ_PASSWORD:guest}

datum:
  rabbitmq:
    customer-events-exchange: datum001.topic
    customer-created-routing-key: usuarios.criados.cliente
    customer-status-change-queue: customer_status_changed
  score-service:
    base-url: http://${SCORE_SERVICE_HOST:localhost}:${SCORE_SERVICE_PORT:8090}
